<?php

namespace WebMeta\CommonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EquipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipeRepository extends EntityRepository
{
    
     /**
     * Récupère un nom d'équipe par son ID
     * @param int $id_equipe 
     * @return array
     */
    public function findNomByIdEquipe($id_equipe) {
        
        return $this->getEntityManager()
                        ->createQuery(
            'SELECT e.nom
            FROM WebMetaCommonBundle:Equipe e
            WHERE e.id = :idEquipe')->setParameter('idEquipe', $id_equipe)->getResult();
                 
    }  

}
