<?php

namespace WebMeta\CommonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InvitationEquipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvitationEquipeRepository extends EntityRepository
{
    
    /**
     * Récupère une liste d'équipe dont le membre à fait la demande
     * @param int $id_compte id du compte faisant la demande
     * @param string $statut statut de la demande
     * @param string $demandeur 
     * @return array
     */
    public function findAllDemandeEquipe($id_compte, $statut = 'en attente', $demandeur = 'joueur') {
        
        $query = $this->getEntityManager()->createQuery('SELECT ie.id_equipe FROM WebMetaCommonBundle:InvitationEquipe ie WHERE ie.id_compte = ?1 AND ie.statut = ?2 AND ie.demandeur = ?3');
        $query->setParameter(1, $id_compte);
        $query->setParameter(2, $statut);
        $query->setParameter(3, $demandeur);
        return $query->getResult();
        
    }

}
