<?php

namespace WebMeta\CommonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    
     /**
     * Récupère la liste des messages non lu d'un compte
     * @param int $id_compte
     * @return array
     */
    public function findMessageNonLu($id_compte) {
        
        return $this->getEntityManager()
                        ->createQuery(
            'SELECT m.id
            FROM WebMetaCommonBundle:Message m
            WHERE m.id = :idCompte
            AND m.statut = :statut' )->setParameter('idCompte', $id_compte)->setParameter('statut', "non-lu")->getResult();
                 
    }

        
     /**
     * Récupère la liste des messages non lu d'un compte
     * @param int $id_expediteur 
     * @return array
     */
    public function findPseudoByIdExpediteur($id_expediteur) {
        
        return $this->getEntityManager()
                        ->createQuery(
            'SELECT c.pseudo
            FROM WebMetaCommonBundle:Compte c
            WHERE c.id = :idExpediteur')->setParameter('idExpediteur', $id_expediteur)->getResult();
                 
    }    
}
