<?php

namespace WebMeta\CommonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository {
    
    /**
     * Récupère une liste de page selon un nom de catégorie
     * @param string $unNomCategorie
     * @return array
     */
    public function findAllPageByNomCategorie($unNomCategorie = null) {
        
        if ($unNomCategorie != null) {
            return $this->getEntityManager()
                            ->createQuery(
                'SELECT p
                FROM WebMetaCommonBundle:Page p
                WHERE p.nom_categorie = :nomCat')->setParameter('nomCat', $unNomCategorie)->getResult();
        } else {
            return $this->getEntityManager()
                            ->createQuery(
                'SELECT p
                FROM WebMetaCommonBundle:Page p')->getResult();
        }
                 
    }

}
