<?php

namespace WebMeta\CommonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RessourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RessourceRepository extends EntityRepository
{
    
     /**
     * Récupère une liste de ressources
     * @param int $id_compte id du compte
      * @param boolean $is_public public/privé
     * @return array
     */
    public function findAllRessource($id_compte,$is_public) {
        
        return $this->getEntityManager()
                        ->createQuery(
            'SELECT r
            FROM WebMetaCommonBundle:Ressource r
            WHERE r.id_compte = :idCompte
            AND r.is_public = :isPublic
            ORDER BY r.date_publication ASC')
                ->setParameter('idCompte', $id_compte)
                ->setParameter('isPublic', $is_public)
                ->getResult();
    }
}
