parameters:
#    web_meta_common.example.class: WebMeta\CommonBundle\Example

services:
#    web_meta_common.example:
#        class: %web_meta_common.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
